### ISSUE TITLE
collision stats for experimental functions

### ISSUE THREAD

**Issue by gotjoshua** [bryc/code#16]
thanks for sharing all your great explorations!
do you have comparison charts available for your experimental functions?

**Comment by bryc** [comment]
Oops, somehow this issue slipped by me. Sorry! 😞 

I didn't bother to measure the experimental ones, as they still may change. I plan to retest all the hash functions eventually, and may include the experimental ones as well.

But they should be roughly comparable to the MurmurHash and xxHash variants. Speed in JS is mostly determined by number of operations and number of loop iterations (if a function reads multiple bytes at a time, that's a considerable speed boost; if the function uses less operations in general, that is also a speed boost).
