### ISSUE TITLE
PRNG.md: link more directly to sources

### ISSUE THREAD

**Issue by jason-s** [bryc/code#3]
re: https://github.com/bryc/code/blob/master/jshash/PRNGs.md

What a great, concise listing of PRNGs for Javascript! Is there any way you could link to the original sources (where possible)? It would help make it easy to verify that the algorithm you posted is consistent with the originally-published algorithm.

(for example, http://prng.di.unimi.it/ and http://prng.di.unimi.it/xoshiro128starstar.c for `xoshiro128**`)

**Comment by bryc** [comment]
Sure, I will add a reference section. For now, I believe these are the original sources of most:

JSF - https://burtleburtle.net/bob/rand/smallprng.html
v3b - http://cipherdev.org/v3b.c
mulberry32 - https://gist.github.com/tommyettinger/46a874533244883189143505d203312c
Tyche - https://www.researchgate.net/publication/233997772 (original paper)
sfc32 - http://pracrand.sourceforge.net/ (code is in package)
gjrand32 - http://gjrand.sourceforge.net/ (code is in package)
MWC - http://www.cse.yorku.ca/~oz/marsaglia-rng.html (copy of usenet post for KISS99)
Xorshift - https://www.jstatsoft.org/article/view/v008i14 (original paper)
Xoshiro/Xoroshiro - http://prng.di.unimi.it/
Alea - [better-random-numbers-for-javascript-mirror/.../Alea.js](https://github.com/nquinlan/better-random-numbers-for-javascript-mirror/blob/master/support/js/Alea.js)

My version of SplitMix32 is a bit unique--fairly certain it came from ideas [here](http://marc-b-reynolds.github.io/shf/2017/09/27/LPRNS.html), [here](http://gee.cs.oswego.edu/dl/papers/oopsla14.pdf) and [here](http://xoshiro.di.unimi.it/splitmix64.c). It is basically just the [fmix32](https://github.com/aappleby/smhasher/blob/master/src/MurmurHash3.cpp#L68) function of MurmurHash turned into a PRNG using [Weyl sequences](https://en.wikipedia.org/wiki/Weyl_sequence).

For LCG, it's super simple, you can read about at [Wikipedia](https://en.wikipedia.org/wiki/Lehmer_random_number_generator)

**Comment by bryc** [comment]
Should be much clearer now. Thanks for the suggestion :)
