### ISSUE TITLE
PRNG non-decimal outputs

### ISSUE THREAD

**Issue by plonibarploni** [bryc/code#5]
I've been following the instructions [here](https://github.com/bryc/code/blob/master/jshash/PRNGs.md#addendum-a-seed-generating-functions), but all my outputs begin with a decimal point (e.g. `0.14844651753082871`). This is similar to `Math.random()`, but I'm looking for something more like `Crypto.getRandomValues()`. Is it not possible to accomplish this, or am I doing something wrong?

**Comment by bryc** [comment]
It's supposed to return a float to match `Math.random`. It does this using the divisor `/ 4294967296`. You can remove the division and it will give you 32-bit numbers instead.

In that sense, the following two methods are equivalent:

```js
window.crypto.getRandomValues( new Uint32Array(4) ); 

// vs
function mulberry32(a) {
    return function() {
      a |= 0; a = a + 0x6D2B79F5 | 0;
      var t = Math.imul(a ^ a >>> 15, 1 | a);
      t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
      return ((t ^ t >>> 14) >>> 0); // notice the removed division
    }
}
var rand = mulberry32(0xbaddcafe);
new Uint32Array(4).map( () => rand() );
```

**Comment by plonibarploni** [comment]
I tested it and it works. Thank you!
